services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=japanese_db
    volumes:
        - postgres_data:/var/lib/postgresql/data
    ports:
        - "5432:5432"

volumes:
  postgres_data: